name: Ejecutar masterhand.py al haber cambios

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  ejecutar-masterhand:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ONEPAGE_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar masterhand.py
      run: |
        python3 masterhand.py docu/ documentation/

    - name: Subir carpeta 'documentation' a la rama 'gh-pages'
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git clone --branch gh-pages --single-branch https://github.com/${{ github.repository }}.git gh-pages    
        cp -R documentation/* gh-pages/
        cd gh-pages
        git add documentation
        git commit -m "Actualización de la documentación"
        git push origin gh-pages
