name: Ejecutar masterhand.py al haber cambios

on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar-masterhand:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ONEPAGE_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar masterhand.py
      run: |
        python3 masterhand.py docu/ documentation/
        
    - name:  Subir carpeta 'documentation' a la rama 'gh-pages'
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        ls
        git add -A documentation/
        git commit -m "Documentacion Actualizada"
        git push gh-pages
